export enum DietaryTagsEnum {
  GLUTEN_FREE = 'GLUTEN_FREE',
  HALAL = 'HALAL',
  HEATHIER_CHOICE = 'HEATHIER_CHOICE',
  HYPOALLERGENIC = 'HYPOALLERGENIC',
  LACTOSE_FREE = 'LACTOSE_FREE',
  ORGANIC = 'ORGANIC',
  TRANS_FAT_FREE = 'TRANS_FAT_FREE',
  VEGETARIAN = 'VEGETARIAN',
}
