export enum VerifyEmailTemplateIdEnum {
  SIGN_UP = 7,
  SIGN_UP_SUCCESS = 9,
  CHANGE_EMAIL = 11,
  CHANGE_EMAIL_SUCCESS = 10,
  CHANGE_PASSWORD = 13,
  CHANGE_PASSWORD_LINK = 8,
  CHANGE_PASSWORD_ERROR = 14,
  CHANGE_PASSWORD_SUCCESS = 15,
}
