export enum CategotyTypeEnum {
  PRIME_CATEGORY = 'PRIME_CATEGORY',
  SUB_CATEGORY = 'SUB_CATEGORY',
  BASIC_CATEGORY = 'BASIC_CATEGORY',
}

export enum PrimeCategoryEnum {
  FRUITS_VEGETABLES = 'FRUITS_VEGETABLES',
  DRINKS = 'DRINKS',
  RICE_NOODLES_COOKING_INGRIDIENTS = 'RICE_NOODLES_COOKING_INGRIDIENTS',
  FOOD_CUPBOARD = 'FOOD_CUPBOARD',
  DAIRY_CHILLED_EGGS = 'DAIRY_CHILLED_EGGS',
  BEER_WINE_SPIRITS = 'BEER_WINE_SPIRITS',
  BAKERY = 'BAKERY',
  FROZEN = 'FROZEN',
  MEAT_SEAFOOD = 'MEAT_SEAFOOD',
}

export enum SubCategoryEnum {
  JUICES = 'JUICES',
  EGGS = 'EGGS',
  FRUITS = 'FRUITS',
  VEGETABLES = 'VEGETABLES',
  CANNED_FOOD = 'CANNED_FOOD',
  BEEF_LAMB = 'BEEF_LAMB',
  FISH_SEAFOOD = 'FISH_SEAFOOD',
  DRIED_FOOD = 'DRIED_FOOD',
  OIL = 'OIL',
  FROZEN_FOOD = 'FROZEN_FOOD',
}

export enum BasicDrinksSubCategoryEnum {
  APPLE_JUICE = 'APPLE_JUICE',
  ORANGE_JUICE = 'ORANGE_JUICE',
}

export enum BasicDairyChilledAndEggsSubCategoryEnum {
  FRESH_EGGS = 'FRESH_EGGS',
}

export enum BasicFruitsSubCategoryEnum {
  APPLES_PEARS = 'APPLES_PEARS',
  CITRUS_FRUITS = 'CITRUS_FRUITS',
  TROPICAL_FRUITS = 'TROPICAL_FRUITS',
}

export enum BasicVegetablesSubCategoryEnum {
  BROCCOLI_CAULIFLOWERS = 'BROCCOLI_CAULIFLOWERS',
  BEANS_PEAS = 'BEANS_PEAS',
  BRINJALS_GOURDS = 'BRINJALS_GOURDS',
  CABBAGES_LETTUCES = 'CABBAGES_LETTUCES',
  CUCUMBERS_LADY_FINGERS = 'CUCUMBERS_LADY_FINGERS',
  CORNS = 'CORNS',
  FROZEN_VEGETABLES = 'FROZEN_VEGETABLES',
  GARLIC_GINGER_ONIONS = 'GARLIC_GINGER_ONIONS',
  STONE_FRUITS = 'STONE_FRUITS',
  POTATOES_ROOTS = 'POTATOES_ROOTS',
  TOMATOES = 'TOMATOES',
}

export enum BasicCannedFoodSubCategoryEnum {
  CANNED_VEGETABLES = 'CANNED_VEGETABLES',
}

export enum BasicBeadAndLambSubCategoryEnum {
  BEANS_SEEDS_NUTS = 'BEANS_SEEDS_NUTS',
}

export enum BasicFishAndSeaFoodSubCategoryEnum {
  FRESH_FISH_SEAFOOD = 'FRESH_FISH_SEAFOOD',
}

export enum BasicDriedFoodSubCategoryEnum {
  BEANS_SEEDS_NUTS = 'BEANS_SEEDS_NUTS',
}

export enum BasicOilSubCategoryEnum {
  BEANS_SEEDS_NUTS = 'BEANS_SEEDS_NUTS',
}

export enum BasicFrozenFoodSubCategoryEnum {
  FROZEN_VEGETABLES = 'FROZEN_VEGETABLES',
}
