export enum JobEnum {
  SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS',
  SUBSCRIBE_ONBOARD = 'SUBSCRIBE_ONBOARD',
  SUBSCRIBE_AUTHOR = 'SUBSCRIBE_AUTHOR',
  MOST_POPULAR_PRODUCTS = 'MOST_POPULAR_PRODUCTS',
}

// export enum JobPriorityEnum {
//   SIGNUP,
//   VERIFY_CODE,
//   CHANGE_EMAIL,
//   CHANGE_PASSWORD,
//   CHANGE_PASSWORD_LINK,
//   SUBSCRIBE_ONBOARD,
//   SUBSCRIBE_AUTHOR,
//   SUBSCRIBE_SUCCESS,
//   SIGN_UP_SUCCESS,
//   CHANGE_EMAIL_SUCCESS,
//   CHANGE_PASSWORD_ERROR,
//   CHANGE_PASSWORD_SUCCESS,
//   MOST_POPULAR_PRODUCTS,
// }
