export enum UnsubscribeExpirationEnum {
  UNSUBSCRIBE_EXPIRATION = 30 * 24 * 60 * 60 * 1000, // 30 days
}

export enum UnsubscribeCategoryEnum {
  ALL = 'ALL',
  MARKETING = 'MARKETING',
  DEV_NEWS = 'DEV_NEWS',
  BLOG_NEWS = 'BLOG_NEWS',
}

export enum UnsubscribeReasonEnum {
  TOO_MANY_EMAILS = 'TOO_MANY_EMAILS',
  CONTENT_NOT_RELEVANT_TO_ME = 'CONTENT_NOT_RELEVANT_TO_ME',
  FOUND_BETTER_ALTERNATIVES = 'FOUND_BETTER_ALTERNATIVES',
  NO_LONGER_INTERESTED_IN_THIS_TOPIC = 'NO_LONGER_INTERESTED_IN_THIS_TOPIC',
  EMAIL_TOO_FREQUENT = 'EMAIL_TOO_FREQUENT',
  CONTENT_QUALITY_ISSUES = 'CONTENT_QUALITY_ISSUES',
  OTHER_REASON = 'OTHER_REASON',
}
